FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    build-essential \
    vim \
    curl \
    wget \
    net-tools

WORKDIR /app

COPY . /app

# ✅ FIX HERE
RUN pip3 install --break-system-packages -r requirements.txt

EXPOSE 8000

CMD ["python3", "app.py"]
